# -*- coding: utf-8 -*-
"""Coplian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WTQ_HVrcFv8PMHhS4T7TB4HWdrfFc01S
"""

# Complaint Resolution mail
import smtplib, ssl

port = 465  # For SSL
smtp_server = "smtp.gmail.com"
sender_email = "prajakta.dashrath@mitaoe.ac.in"  # Enter your address
receiver_email = "prajakta.dashrath@mitaoe.ac.in"  # Enter receiver address
password = "nabe gtnu bryw njyv"
message = """\
Subject: RESOLVED COMPLAINT

We resolved your compaint ."""

context = ssl.create_default_context()
with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
    server.login(sender_email, password)
    server.sendmail(sender_email, receiver_email, message)

import tensorflow as tf
tf.test.gpu_device_name()

# Complaint Resolution mail
import smtplib, ssl

date_input = '2018-03-23' # @param {type:"date"}

print(date_input)
port = 465  # For SSL
smtp_server = "smtp.gmail.com"
sender_email = "prajakta.dashrath@mitaoe.ac.in"  # Enter your address
receiver_email = "prajaktadashrath@gmail.com"  # Enter receiver address
password = input("Type your password and press enter: ")
message = """\
Subject: Complaint Resolution Reminder

We resolved your compaint ."""
message1 = date_input
print(date_input)
context = ssl.create_default_context()
with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
    server.login(sender_email, password)
    server.sendmail(sender_email, receiver_email, message)

!pip install -q gwpy

Student = True # @param {type:"boolean"}
print(Student)

Faculty = False # @param {type:"boolean"}
print(Faculty)

date_input = '2018-03-23' # @param {type:"date"}

print(date_input)

#Choose the compiant heads
Section = "HR" # @param ["HR", "Exam", "Student"]
print('You have selected', Section)
Deparment = "Software Engineering" # @param ["Computer","Software Engineering","AIML","DataScience","IT","E and TC","mechanical","Civil"]
Complaint = "Unable to register leave on ERP" # @param {"type":"string","placeholder":"Enter your Complain"}
port = 465  # For SSL
smtp_server = "smtp.gmail.com"
sender_email = "prajakta.dashrath@mitaoe.ac.in"  # Enter your address
receiver_email = "prajaktadashrath@gmail.com"  # Enter receiver address
password = "nabe gtnu bryw njyv"
message2 = """Subject: NEW COMPLAINT\n\n"""
message = message2 + Section  + Deparment + Complaint
print(message)

context = ssl.create_default_context()
with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
    server.login(sender_email, password)
    server.sendmail(sender_email, receiver_email, message)

# @title Default title text
Student = True # @param {type:"boolean"}
print(Student)
Faculty = False # @param {type:"boolean"}
print(Faculty)
date = '2018-03-23' # @param {"type":"date"}
print(date)
Section = "Student" # @param ["Student","Exam","Admin","Faculty","Staff","Store"]
Deparment = "IT" # @param ["Computer","Software Engineering","AIML","DataScience","IT","E and TC","mechanical","Civil"]
ID = 98 # @param {"type":"number","placeholder":"Enter your ID"}
Name = "Prajakta Dashrath " # @param {"type":"string","placeholder":"Enter your name "}
PhoneNumber = 7498205269 # @param {"type":"number","placeholder":"Enter your Phone Number"}
Email = "prajakta.dashrath@mitaoe.ac.in" # @param {"type":"string", "placeholder":"Enter your mail "}
Complaint = "Unable to see marks" # @param {"type":"string","placeholder":"Enter your Complain"}
#PhoneNumber = 0 # @param {"type":"number","placeholder":"Enter Your phone number"}

#Inserting data using pyton sqlite
import  sqlite3
conn  =  sqlite3 . connect ( 'mitaoe.db' )
cursor  =  conn.cursor ()

cursor.execute("CREATE TABLE MITComplaints(Student char (30), Faculty char (30), date char(30),Section char(30), Deparment char(30), ID n(5), Name char(30),PhoneNumber char(30), Email char(30),Complaint char(30));")


Student = Student
Faculty = Faculty
date = date
Section  = Section
Deparment = Deparment
ID = ID
Name = Name
Email = Email
PhoneNumber = PhoneNumber
Complaint = Complaint

cursor.execute("""
INSERT INTO MITComplaints(Student,Faculty,date,Section,Deparment,ID,Name,Email,PhoneNumber,Complaint)
VALUES (?,?,?,?,?,?,?,?,?,?)
""", (Student,Faculty,date,Section,Deparment,ID,Name,Email,PhoneNumber,Complaint))
conn.commit ()
print ( 'Compliant Registered  successfully.' )
conn . close ()
if (conn):
  conn.close()
  print("\n We will try to resolve your compaint soon .")

#basic code for Display record
import  sqlite3
conn  =  sqlite3 . connect ( 'mitaoe.db' )
cursor  =  conn.cursor ()

cursor.execute("SELECT * FROM MITComplaints")
MComplaints = cursor.fetchall()

for MComplaint in MComplaints:
    print(MComplaint)

#Display record using Data Frame
import  sqlite3
import pandas as pd
db = sqlite3.connect("mitaoe.db")
query = """
  select * from MITComplaints
"""
df = pd.read_sql_query(query,db)
df.head()

#Inserting data using pyton sqlite
import  sqlite3
conn  =  sqlite3 . connect ( 'mydatabase.db' )
cursor  =  conn.cursor ()

#cursor.execute("CREATE TABLE MComplaints(Faculty_ID n(5), Name char(30), Email char(30), Phone_No n(5), day char(30),Detail_Description char(30));")


Faculty_ID = input('Faculty_ID:')
Name = input('Name:')
Email = input('Email:')
Phone_No = input('Phone_No:')
day = input('day:')
Detail_Description = input('Detail_Description:')
cursor.execute("""
INSERT INTO MComplaints(Faculty_ID, Name, Email, Phone_No, day, Detail_Description)
VALUES (?,?,?,?,?,?)
""", (Faculty_ID, Name, Email, Phone_No,day,Detail_Description))
conn.commit ()
print ( 'Compliant Registered  successfully.' )
conn . close ()
if (conn):
  conn.close()
  print("\n We will try to resolve your compaint soon .")

!pip install pyqrcode
!pip install pypng

import pyqrcode
import png
from pyqrcode import QRCode

!pip install amzqr

CREATE TABLE documents(
    id INTEGER PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    data BLOB NOT NULL
);

!pip install pyqrcode

!pip install pypng

!pip install qrcode

docker pull mcr.microsoft.com/windows/nanoserver:ltsc2022

import pyqrcode
import png
from PIL import Image

#inserting website name
s = input("Enter your website: ")
print(s)
url = pyqrcode.create(s)

#saving image
img = "qr-code.png"
url.png(img, scale=10)

#opening image
im=Image.open(img)

#show
im



uploaded = files.upload()
Image('th.jpg')

Image('th.jpg')

#Feedback form
lang = input("Enter Your rating from 1 to 5")
from IPython.display import Image
match lang:
    case "1":
      import matplotlib.pyplot as plt
      import matplotlib.image as mpimg

      img = mpimg.imread('th.jpg') #Replace "image.jpg" with the path of your image
      plt.imshow(img)
      plt.axis('off')
      plt.show()
    case "2":
      print("**")
    case "3":
       print("***")
    case "4":
       print("****")
    case "5":
       print("*****")
    case _:
      print("other")
      a=input()
      print(a)

# Final Code to display an image
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img = mpimg.imread('3.png') #Replace "image.jpg" with the path of your image
plt.imshow(img)
plt.axis('off')
plt.show()

Section = "Student" # @param ["Student","Exam","Admin","Faculty","Staff","Store"]
#lang = input("What's the programming language you want to learn? ")

match Section:
    case "Student":
      import smtplib, ssl
      port = 465  # For SSL
      smtp_server = "smtp.gmail.com"
      sender_email = "prajakta.dashrath@mitaoe.ac.in"  # Enter your address
      receiver_email = "prajakta.dashrath@mitaoe.ac.in"  # Enter receiver address
      password = "nabe gtnu bryw njyv"
      mail_Subject = "New Complaint"
      message = """
          Your Compliant is resolved.
      """
      context = ssl.create_default_context()
      with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
        server.login(sender_email, password)
        server.sendmail(sender_email, receiver_email, message)

    case "Python":
        print("You can become a Data Scientist")

    case "PHP":
        print("You can become a backend developer")

    case "Solidity":
        print("You can become a Blockchain developer")

    case "Java":
        print("You can become a mobile app developer")
    case _:
        print("The language doesn't matter, what matters is solving problems.")

# Commented out IPython magic to ensure Python compatibility.
# Import Python Packages
import smtplib
# Set Global Variables
gmail_user = 'prajakta.dashrath@mitaoe.ac.in'
gmail_password = 'nabe gtnu bryw njyv'
# Create Email
mail_from = gmail_user
mail_to = 'prajakta.dashrath@mitaoe.ac.in'
mail_subject = 'Hello'
mail_message_body = 'Hello World!'

mail_message = '''\
From: %s
To: %s
Subject: %s
# %s
''' % (mail_from, mail_to, mail_subject, mail_message_body)
# Sent Email
server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
server.login(gmail_user, gmail_password)
server.sendmail(mail_from, mail_to, mail_message)
server.close()

# Complaint Resolution mail
import smtplib, ssl

port = 465  # For SSL
smtp_server = "smtp.gmail.com"
sender_email = "prajakta.dashrath@mitaoe.ac.in"  # Enter your address
receiver_email = "prajakta.dashrath@mitaoe.ac.in"  # Enter receiver address
password = "nabe gtnu bryw njyv"
message = """\
Subject: RESOLVED COMPLAINT

We resolved your compaint ."""

context = ssl.create_default_context()
with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
    server.login(sender_email, password)
    server.sendmail(sender_email, receiver_email, message)

# Complaint Resolution mail
import smtplib, ssl

port = 465  # For SSL
smtp_server = "smtp.gmail.com"
sender_email = "prajakta.dashrath@mitaoe.ac.in"  # Enter your address
receiver_email = "prajakta.dashrath@mitaoe.ac.in"  # Enter receiver address
password = "nabe gtnu bryw njyv"
message = """\
Subject: RESOLVED COMPLAINT

We resolved your compaint ."""

context = ssl.create_default_context()
with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
    server.login(sender_email, password)
    server.sendmail(sender_email, receiver_email, message)

# Complaint Resolution mail
import smtplib, ssl

port = 465  # For SSL
smtp_server = "smtp.gmail.com"
sender_email = "prajakta.dashrath@mitaoe.ac.in"  # Enter your address
receiver_email = "prajakta.dashrath@mitaoe.ac.in"  # Enter receiver address
password = "nabe gtnu bryw njyv"
message = """\ Subject: RESOLVED COMPLAINT

We resolved your compaint ."""

context = ssl.create_default_context()
with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
    server.login(sender_email, password)
    server.sendmail(sender_email, receiver_email, message)

!pip install colabcode
!pip install fastapi